# .travis.yml 
language: python
python:
  - "2.7"
env:
  - NODE_VERSION="6.9.1"

before_install:
  - nvm install $NODE_VERSION
  - npm install -g mocha
  
install: 
  - pip install konlpy
  - npm install
  
before_script:
  - curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | sudo bash

script: 
  - mocha unit_test/deudnunda_test.js